# Generated by Django 5.2 on 2025-04-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('waiter', 'Garson'), ('customer', 'Müşteri')], default='waiter', max_length=20),
        ),
    ]
