# Generated by Django 5.2 on 2025-04-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Alındı'), ('preparing', 'Hazırlanıyor'), ('ready', 'Hazır'), ('served', 'Serviste'), ('paid', 'Ödendi')], default='received', max_length=20),
        ),
    ]
