# Generated by Django 5.2 on 2025-04-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_table_number_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='masa', max_length=20),
        ),
    ]
